#!/bin/sh

deps='
documentcloud/underscore/underscore.js:underscore.js
douglascrockford/JSON-js/json2.js:json2.js
documentcloud/backbone/backbone.js:backbone.js
dvv/coffee-mongo/lib:mongo
cloudhead/node-static/lib:static
'

lib=lib/node
mkdir -p "$lib"
for dep in $deps; do
	# parse definition
	path=${dep%:*}
	link=${dep##*:}
	author=${path%%/*}
	path=${path#*/}
	git=${path%%/*}
	# fetch the package
	echo link ${author}\'s $git to $link, path $path
	if ! test -d git/${git}; then
		#git clone https://github.com/${author}/${git}.git git/${git}
		mkdir -p git/${git}
		wget -ct3 -q --progress=bar --no-check-certificate http://nodeload.github.com/${author}/${git}/tarball/master -O- | tar -xzf- --strip 1 -C git/${git}
		cd git/${git}
		#if test -f Makefile; then
		#	make
		#fi
		if test -f wscript; then
			node-waf configure build
		fi
		cd ../..
	fi
	# symlink entry point
	test -e "$lib/$link" || ln -s "../../git/$path" "$lib/$link"
done
