#!/bin/sh

deps='
cloudhead/eyes.js/lib/eyes.js:eyes.js
kriszyp/promised-io/lib:promised-io
dvv/json-schema:json-schema
kriszyp/compose/lib/compose.js:compose.js
documentcloud/underscore/underscore.js:underscore.js
documentcloud/underscore/underscore.js:../js/underscore.js
edtsech/underscore.string/lib/underscore.string.js:../js/underscore.string.js
Modernizr/Modernizr/modernizr.js:../../public/js/modernizr.js
douglascrockford/JSON-js/json2.js:../js/json2.js
kriskowal/es5-shim/es5-shim.js:../js/es5-shim.js
documentcloud/backbone/backbone.js:../js/backbone.js
dvv/schema2form/index.js:../js/schema2form.js
dvv/rql/lib:rql
dvv/rql/lib:../js/rql
felixge/node-formidable/lib/formidable:formidable
maqr/node-xml2js/lib:xml2js
astro/node-expat/build/default/node-expat.node:node-expat.node
Poetro/node-xml2js-expat/lib/xml2js.js:xml2js.js
tautologistics/node-htmlparser/lib/htmlparser.js:htmlparser.js
isaacs/sax-js/lib/sax.js:sax.js
dvv/coffee-mongo/lib:mongo
dvv/simple/lib:simple
mranney/node_redis:redis
cloudhead/node-static/lib:static
jed/cookie-node/index.js:cookie.js
bentomas/node-mime:mime
3rd-eden/node-useragent/useragent.js:useragent.js
weaver/node-mail/lib/mail:mail
miksago/node-websocket-server/lib:ws-server
learnboost/socket.io-node:io
'

# download dependencies
lib=lib/node
jslib="$lib/../js"
mkdir -p "$lib" "$jslib"
for dep in $deps; do
	# skip comments
	case "$dep" in
		\#*) continue ;;
	esac
	# parse definition
	path=${dep%:*}
	link=${dep##*:}
	author=${path%%/*}
	path=${path#*/}
	git=${path%%/*}
	# fetch the package
	echo link ${author}\'s $git to $link, path $path
	#continue
	if ! test -d git/${git}; then
		#git clone https://github.com/${author}/${git}.git git/${git}
		mkdir -p git/${git}
		wget -ct3 -q --progress=bar --no-check-certificate http://nodeload.github.com/${author}/${git}/tarball/master -O- | tar -xzf- --strip 1 -C git/${git}
		cd git/${git}
		#if test -f Makefile; then
		#	make
		#fi
		if test -f wscript; then
			node-waf configure build
		fi
		cd ../..
	fi
	# symlink entry point
	if test "Q$link" != 'Q'; then
		test -e "$lib/$link" || ln -s "../../git/$path" "$lib/$link"
	fi
done

# minify client-side scripts

cat \
	$jslib/json2.js \
	$jslib/es5-shim.js \
	$jslib/underscore.js \
	$jslib/underscore.string.js \
	$jslib/backbone.js \
	public/js/jquery.textchange.min.js \
	$jslib/jquery.tokeninput.js \
	$jslib/schema2form.js \
	\
> public/js/bundle.js
#| build/jsmin > bundle.js

#	$jslib/modernizr.js
